{% set name = "cnmaps" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Clarmy/cnmaps/archive/refs/tags/{{ version }}.tar.gz
  sha256: 267ac4ab75b3eb4cbc87d5aa7227c32aa6f7e1eec7ac8b7fccf9cc11729552ec

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - Cartopy >=0.19.0
    - Shapely
    - numpy
    - netCDF4
    - geopandas
    - Fiona
    - geojson

test:
  imports:
    - cnmaps
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Clarmy/cnmaps
  summary: 'cnmaps is a python package that make drawing China maps more easily. '
  description: |
    cnmaps is a python package that make drawing China maps more easily. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Clarmy/cnmaps

extra:
  recipe-maintainers:
    - Clarmy
