{% set name = "cnmaps" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Clarmy/cnmaps/archive/refs/tags/{{ version }}.tar.gz
  sha256: 88d641c29f1e573082cdac1528181411a0a856696dae65ce1e422f60cd64bdcd

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - Cartopy >=0.22.0
    - Shapely >=1.8.0,<2.0
    - numpy >=1.21.5
    - netCDF4 >=1.5.8
    - geopandas >=0.10.2
    - Fiona >=1.8.20
    - geojson >=2.5.0
    - orjson >=3.7.11
    - numba >=0.56.0
    - poppler >=22.12.0
    - scipy >=1.8

test:
  imports:
    - cnmaps
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip list

about:
  home: https://github.com/Clarmy/cnmaps
  summary: 'cnmaps is a python package that make drawing China maps more easily. '
  description: |
    cnmaps is a python package that make drawing China maps more easily. 
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/Clarmy/cnmaps

extra:
  recipe-maintainers:
    - Clarmy
